{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-idea",
    "version": "1.7.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "publishedCompile",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "1.7.20"
          }
        }
      ]
    },
    {
      "name": "publishedRuntime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "1.7.20"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-idea-1.7.20.jar",
          "url": "kotlin-gradle-plugin-idea-1.7.20.jar",
          "size": 109678,
          "sha512": "3e11bf15ae1a741bc49b5605f957c34e2340089d2bcaac3d4dc16be7d014108ba7a769ebb5583a3b36a5bf7b712a36bce192a38e5044fe9e1356a86bdb6b4ae4",
          "sha256": "d11bb085408a0b9c6ec1265ebc069fb771c494f0904fb641fcf02354bcd56b1d",
          "sha1": "47cde176ecd0fcf5a8ef2a5d0a020372bf69bb93",
          "md5": "5d193eaa112a60978ab12350d12360b9"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-idea",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-idea-1.7.20-test-fixtures.jar",
          "url": "kotlin-gradle-plugin-idea-1.7.20-test-fixtures.jar",
          "size": 56555,
          "sha512": "d3affb4870e29fba8449b72ab91ca10c12cdaba36bd5af3acbddaf7a94a98f878114bf9dff8df24e20bb21e4629fed731a40eff9228d88921dd3507b5af46e48",
          "sha256": "5a641e08bc41d4c8c28541711a760d5d011424881e1429c43a61be9928e98a9f",
          "sha1": "ae97917f9fdcd189c6e254321a7a481ff949c881",
          "md5": "e827295e5193244a491239cc1236dd4a"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-idea-test-fixtures",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-tooling-core",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-idea-proto",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-idea",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-idea-1.7.20-test-fixtures.jar",
          "url": "kotlin-gradle-plugin-idea-1.7.20-test-fixtures.jar",
          "size": 56555,
          "sha512": "d3affb4870e29fba8449b72ab91ca10c12cdaba36bd5af3acbddaf7a94a98f878114bf9dff8df24e20bb21e4629fed731a40eff9228d88921dd3507b5af46e48",
          "sha256": "5a641e08bc41d4c8c28541711a760d5d011424881e1429c43a61be9928e98a9f",
          "sha1": "ae97917f9fdcd189c6e254321a7a481ff949c881",
          "md5": "e827295e5193244a491239cc1236dd4a"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-idea-test-fixtures",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-idea-1.7.20-javadoc.jar",
          "url": "kotlin-gradle-plugin-idea-1.7.20-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-idea-1.7.20-sources.jar",
          "url": "kotlin-gradle-plugin-idea-1.7.20-sources.jar",
          "size": 15619,
          "sha512": "e7cbd3a27fa127a91c063415dfd326a01726337437c91f5cb56f5868b881110595b8099e71f5d2a00b2bff219db57c62dc31ed265ac70c98a2b952f77e8de641",
          "sha256": "13e6ca36734157315f13b048bfde71fe7b6e6023e3f644ed5e84f710a0ee9a85",
          "sha1": "f9247c3afc3e01df9ef36c5012421936ee2fe070",
          "md5": "17306a17080f5a437dcaeaec11788fa4"
        }
      ]
    }
  ]
}
