{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-model",
    "version": "1.7.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-javadoc.jar",
          "size": 316676,
          "sha512": "2facbc7a0cf2eaa2d3f93a889dd7b2987f1795af82701d1eb3dcb2379b5de2226366abdfd2f92eb2ca6063e508665b23a0639faa325358b4c33f871db728b153",
          "sha256": "71cdde5f294fe4a2e394dae81aec26c5208cb268e45d289ab585ce7c9d43baab",
          "sha1": "696d415639606d39f9196f273631c64d7186f2ce",
          "md5": "193738ddd06c111dcfed90a37741160c"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20.jar",
          "size": 12104,
          "sha512": "9487267adae8cfcf45c880ef137b25ffbbcc1e434424d854e94eaaa1104fb447c8c355ea96cc2d462989dc70e298e2c4627b872db34df4df2a1385adac4fb4db",
          "sha256": "d982f3e631631875dd340e0413e814ff31066d75172c91c4d4c9afabaeaaaf43",
          "sha1": "ee10b25667d827bc6c2f2520fa43e1a5079ed151",
          "md5": "d8c7cae3fd93755598a6839634bbe7ee"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20.jar",
          "size": 12104,
          "sha512": "9487267adae8cfcf45c880ef137b25ffbbcc1e434424d854e94eaaa1104fb447c8c355ea96cc2d462989dc70e298e2c4627b872db34df4df2a1385adac4fb4db",
          "sha256": "d982f3e631631875dd340e0413e814ff31066d75172c91c4d4c9afabaeaaaf43",
          "sha1": "ee10b25667d827bc6c2f2520fa43e1a5079ed151",
          "md5": "d8c7cae3fd93755598a6839634bbe7ee"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle70-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle70-javadoc.jar",
          "size": 316676,
          "sha512": "2facbc7a0cf2eaa2d3f93a889dd7b2987f1795af82701d1eb3dcb2379b5de2226366abdfd2f92eb2ca6063e508665b23a0639faa325358b4c33f871db728b153",
          "sha256": "71cdde5f294fe4a2e394dae81aec26c5208cb268e45d289ab585ce7c9d43baab",
          "sha1": "696d415639606d39f9196f273631c64d7186f2ce",
          "md5": "193738ddd06c111dcfed90a37741160c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle70-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle70-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle70.jar",
          "size": 12104,
          "sha512": "9487267adae8cfcf45c880ef137b25ffbbcc1e434424d854e94eaaa1104fb447c8c355ea96cc2d462989dc70e298e2c4627b872db34df4df2a1385adac4fb4db",
          "sha256": "d982f3e631631875dd340e0413e814ff31066d75172c91c4d4c9afabaeaaaf43",
          "sha1": "ee10b25667d827bc6c2f2520fa43e1a5079ed151",
          "md5": "d8c7cae3fd93755598a6839634bbe7ee"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle70.jar",
          "size": 12104,
          "sha512": "9487267adae8cfcf45c880ef137b25ffbbcc1e434424d854e94eaaa1104fb447c8c355ea96cc2d462989dc70e298e2c4627b872db34df4df2a1385adac4fb4db",
          "sha256": "d982f3e631631875dd340e0413e814ff31066d75172c91c4d4c9afabaeaaaf43",
          "sha1": "ee10b25667d827bc6c2f2520fa43e1a5079ed151",
          "md5": "d8c7cae3fd93755598a6839634bbe7ee"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle71JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle71-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle71-javadoc.jar",
          "size": 316676,
          "sha512": "2facbc7a0cf2eaa2d3f93a889dd7b2987f1795af82701d1eb3dcb2379b5de2226366abdfd2f92eb2ca6063e508665b23a0639faa325358b4c33f871db728b153",
          "sha256": "71cdde5f294fe4a2e394dae81aec26c5208cb268e45d289ab585ce7c9d43baab",
          "sha1": "696d415639606d39f9196f273631c64d7186f2ce",
          "md5": "193738ddd06c111dcfed90a37741160c"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle71SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle71-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle71-sources.jar",
          "size": 7329,
          "sha512": "bf4931f33d1a6e109f6942c84e73fffeb90d6355a8260b3201ae40046949c74f1dfd0d37cfa72e96e01916c024f45e536ccd99a60b6b06ecff73fa5487e67bf9",
          "sha256": "47dd7c06f08839879b11cc54f1bb2853a9001bdb40bba4c8cff4b25136c3bf69",
          "sha1": "aeb5ff4377dd0034b5d20098263636ae00a52b4e",
          "md5": "9e325fce327ede5df7e4ce9e4cfdf3ac"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle71ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle71.jar",
          "size": 12104,
          "sha512": "9487267adae8cfcf45c880ef137b25ffbbcc1e434424d854e94eaaa1104fb447c8c355ea96cc2d462989dc70e298e2c4627b872db34df4df2a1385adac4fb4db",
          "sha256": "d982f3e631631875dd340e0413e814ff31066d75172c91c4d4c9afabaeaaaf43",
          "sha1": "ee10b25667d827bc6c2f2520fa43e1a5079ed151",
          "md5": "d8c7cae3fd93755598a6839634bbe7ee"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.20"
        }
      ]
    },
    {
      "name": "gradle71RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.7.20-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-1.7.20-gradle71.jar",
          "size": 12104,
          "sha512": "9487267adae8cfcf45c880ef137b25ffbbcc1e434424d854e94eaaa1104fb447c8c355ea96cc2d462989dc70e298e2c4627b872db34df4df2a1385adac4fb4db",
          "sha256": "d982f3e631631875dd340e0413e814ff31066d75172c91c4d4c9afabaeaaaf43",
          "sha1": "ee10b25667d827bc6c2f2520fa43e1a5079ed151",
          "md5": "d8c7cae3fd93755598a6839634bbe7ee"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.7.20"
        }
      ]
    }
  ]
}
